// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_pU_TTpRzx8LQZWxJC2_IDGh3jZcX7E',
    appId: '1:274493730797:web:947cca4224cb3a5f0f41e4',
    messagingSenderId: '274493730797',
    projectId: 'cravecrush-a04c2',
    authDomain: 'cravecrush-a04c2.firebaseapp.com',
    storageBucket: 'cravecrush-a04c2.appspot.com',
    measurementId: 'G-W3W4YT4WCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmhUKH3wlbpOcBbB91w0e2V5yY8vcQtk',
    appId: '1:274493730797:android:63de7fb21b03a8a00f41e4',
    messagingSenderId: '274493730797',
    projectId: 'cravecrush-a04c2',
    storageBucket: 'cravecrush-a04c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8yUPSZBSZr9Wfjk15WKP8ex-Twp_kMo',
    appId: '1:274493730797:ios:c68869f0eb12545e0f41e4',
    messagingSenderId: '274493730797',
    projectId: 'cravecrush-a04c2',
    storageBucket: 'cravecrush-a04c2.appspot.com',
    iosBundleId: 'com.example.cravecrush',
  );
}
